# -*- coding: utf-8 -*-
"""Iris-Data-Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iyt_sgiaBkgIoL6M6rraUg35uW1aQuGU

#Importing Necessary Libraries
"""

import pandas as pd # Pandas is a powerful library for data manipulation and analysis.
import seaborn as sns # Seaborn is a statistical data visualization library based on Matplotlib
import matplotlib.pyplot as plt # Matplotlib is a comprehensive library for creating static, animated, and interactive visualizations in Python

"""##Loading the Dataset"""

iris = pd.read_csv("Iris.csv") # The iris dataset is now a Pandas DataFrame

"""##Taking a look at the Dataset"""

iris.head()

"""##Checking how many examples we have of each species"""

iris['Species'].value_counts()

"""##1) The distribution of sepal lengths and widths among the Iris species"""

# Creating a scatter plot for sepal lengths and widths, colored by species
sns.scatterplot(x='SepalLengthCm', y='SepalWidthCm', hue='Species', data=iris)
plt.title('Distribution of Sepal Lengths and Widths Among Iris Species')
plt.xlabel('Sepal Length (cm)')
plt.ylabel('Sepal Width (cm)')
plt.legend(title='Species')
plt.show()

"""##Interpretation:
###1) From the scatter plot, we can observe the distribution of sepal lengths and widths for each species of Iris flowers.
###2) Different species are represented by different colors in the plot.
###3) We can see if there are any noticeable patterns or differences in the distribution of sepal lengths and widths among the species.

##2) How does the petal length vary across different Iris species?

###A box plot effectively shows the distribution of a continuous variable (petal length) within different categories
"""

plt.figure(figsize=(8, 6))
sns.boxplot(x='Species', y='PetalLengthCm', data=iris)
plt.title('Variation of Petal Length Across Different Iris Species')
plt.xlabel('Species')
plt.ylabel('Petal Length (cm)')
plt.show()

"""##Interpretation:

###1) The box plot illustrates the distribution of petal lengths for each species of Iris flowers.
###2) The box represents the interquartile range (IQR), with the median marked by a horizontal line inside the box.
###3) The whiskers extend to the minimum and maximum values within 1.5 times the IQR from the first and third quartiles, respectively.
###4) Any points beyond the whiskers are considered outliers.

##3) Is there a relationship between sepal length and petal length?

####To explore the relationship between sepal length and petal length, we can use a scatter plot. This type of plot allows us to visualize the relationship between two continuous variables.
"""

plt.figure(figsize=(8, 6))
sns.scatterplot(x='SepalLengthCm', y='PetalLengthCm', data=iris)
plt.title('Relationship Between Sepal Length and Petal Length')
plt.xlabel('Sepal Length (cm)')
plt.ylabel('Petal Length (cm)')
plt.show()

"""##Interpretation:

###1) In the scatter plot, each point represents an individual iris flower.
###2) The position of each point on the plot corresponds to its sepal length and petal length.
###3) By examining the overall pattern of the points, we can assess whether there's a relationship between sepal length and petal length.
###4) If there's a noticeable trend, such as points clustering in a certain direction, it suggests a correlation between the two variables.

##4) Are there any patterns observable in the pairwise relationships between features (sepal length, sepal width, petal length, petal width)?

###To explore pairwise relationships between features (sepal length, sepal width, petal length, petal width), a pairplot is a useful for visualization.
"""

# Creating a pairplot
sns.pairplot(iris, kind='scatter', diag_kind='hist')
plt.suptitle('Pairwise Relationships Between Features in the Iris Dataset', y=1.02)
plt.show()

"""##Interpretation:

####1) The pairplot displays scatterplots for the pairwise combinations of sepal length, sepal width, petal length, and petal width.
####2) The diagonal of the pairplot shows histograms for each individual feature, allowing us to examine their distributions.
####3) By examining the off-diagonal scatterplots, we can identify patterns or relationships between different features. For example, we may observe clusters of points that indicate a correlation between two features.

##5) Can we distinguish between Iris species based on sepal and petal measurements?

####Yes, we can distinguish between Iris species based on sepal and petal measurements. One way to visualize this is by creating a scatter plot matrix (or pairplot) where the scatterplots are colored by species. This allows us to observe the distribution of data points for each species across different combinations of sepal and petal measurements.
"""

# Creating a pairplot with species distinguished by color
sns.pairplot(iris, hue= 'Species', palette='Dark2')
plt.suptitle('Scatter Plot Matrix of Sepal and Petal Measurements by Species', y=1.02)
plt.show()

"""##Interpretation:

####1) Each scatterplot in the matrix represents a pairwise combination of sepal and petal measurements.
####2) Data points belonging to different Iris species are distinguished by color.
####3)By examining the scatterplots, we can observe how the different species are distributed in the feature space defined by sepal and petal measurements. ####This can help us visually identify patterns or clusters that may indicate separability between species.
"""